### ISSUE TITLE
how to label a patch tumor or nomal?

### ISSUE THREAD

**Issue by swy0915** [Camelyon17/camelyon17#1]
@JooHyun-Lee 
when I get a patch half of tumor, I should label 1 or 0? white is tumor area,black is nomal area
![aaa](https://user-images.githubusercontent.com/16319211/43496127-303a670e-956e-11e8-95ed-60635661549b.png)

**Comment by cv-lee** [comment]
It's up to you.

In this project,
Tumor pixel ratio in the patch < 5% -> Normal
Tumor pixel ratio in the patch > 5% -> Tumor

**Comment by swy0915** [comment]
thank you
